const { VITE_DUMMY_API_URL, VITE_DUMMY_API_KEY, VITE_GOOGLE_CLIENT_ID } =
  import.meta.env;

export const API_URL = VITE_DUMMY_API_URL;
export const API_KEY = VITE_DUMMY_API_KEY;
export const GOOGLE_CLIENT_ID = VITE_GOOGLE_CLIENT_ID;
